### ISSUE TITLE
Problem installing on 10.9.4

### ISSUE THREAD

**Issue by d3v-null** [Chris911/iStats#11]
Hi there,
Was very excited to try this out but i encountered an error installing it on my week-old macbook pro, i7 running 10.9.4. I've never used ruby before so I appologize if I'm missing something but I ran sudo gem install iStats and this was the error:

```
Fetching: sparkr-0.4.1.gem (100%)
Successfully installed sparkr-0.4.1
Fetching: iStats-0.0.9.gem (100%)    
Building native extensions.  This could take a while...
ERROR:  Error installing iStats:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9/ext/osx_stats/gem_make.out
```

Here's the contents of said log file:

```
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h
```

(not sure if this is the correct place to post this :S appologies if this is not the case)

**Comment by kyxap** [comment]
the issue is still not fixed, just got the same problem, and fixed with installation of additional component

**Comment by Voidshot** [comment]
This issue still exists on macOS Sierra 10.12.6 but the fix below still works:

> $ xcode-select --install
> $ xcodebuild --license
> $ sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install iStats

**Comment by kylemart** [comment]
Ran into the same issue on High Sierra, but following @derwentx's advice solved the problem for me. Not sure if it was a typo, or if things have changed since 2014, but `xcodebuild --license` wasn't a valid command on my machine. I ended up doing the following:

```bash
$ xcode-select --install
$ xcodebuild -license
$ sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install iStats
```
