### ISSUE TITLE
undefined method `exists?' for File:Class (NoMethodError)

### ISSUE THREAD

**Issue by jensenbln** [Chris911/iStats#110]
hi, istats stoped working and i get this error message:

/usr/local/lib/ruby/gems/3.2.0/gems/iStats-1.6.1/lib/iStats/settings.rb:29:in `load': undefined method `exists?' for File:Class (NoMethodError)

        if File.exists?(@configDir + @configFile)
               ^^^^^^^^
Did you mean?  exist?
        from /usr/local/lib/ruby/gems/3.2.0/gems/iStats-1.6.1/lib/iStats/command.rb:10:in `execute'
        from /usr/local/lib/ruby/gems/3.2.0/gems/iStats-1.6.1/bin/istats:8:in `<top (required)>'
        from /usr/local/bin/istats:23:in `load'
        from /usr/local/bin/istats:23:in `<main>'
()minimac [11:55:56] ~ $ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin21]
()minimac [11:56:18] ~ $ uname -a
Darwin minimac 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

**Comment by Chris911** [comment]
Fixed in https://github.com/Chris911/iStats/commit/1211bb180d22027d8e78b7f6365d9ae3af32180f and new version released (1.6.2).
