### ISSUE TITLE
no temps reported

### ISSUE THREAD

**Issue by timball** [Chris911/iStats#17]
just installed on a 2010 mac pro via gem . istats totally gets the fan speeds , which is dope , but reports 0.0C for (the only) cpu temp ... which seems wrong . but i'm gonna write a munin plugin to graph cpu and fan stuff right now anyways and hope that a fix can be found . i assume this is something w/ ioreg , but i haz no time right now to understand it .

--timball

ps) please ignore the terrible cut&paste job . my fonts terminal fonts are a bit wonked out . 

```bash
VideoMac-2:~ timball$ istats fan
Total fans in system: 6
Fan 0 speed: 803.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 1 speed: 599.5 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 2 speed: 599.0 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 3 speed: 598.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 4 speed: 1112.75 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 5 speed: 1113.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
VideoMac-2:~ timball$ istats all
--- CPU Stats ---
CPU temp: 0.0┬░C  ÔûüÔûéÔûâÔûàÔûåÔûç

--- Fan Stats ---
Total fans in system: 6
Fan 0 speed: 802.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 1 speed: 599.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 2 speed: 598.0 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 3 speed: 598.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 4 speed: 1113.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç
Fan 5 speed: 1113.25 RPM  ÔûüÔûéÔûâÔûàÔûåÔûç

--- Battery Stats ---
No battery on system
VideoMac-2:~ timball$ istats cpu temp
CPU temp: 0.0┬░C  ÔûüÔûéÔûâÔûàÔûåÔûç
VideoMac-2:~ timball$ istats cpu temperature
CPU temp: 0.0┬░C  ÔûüÔûéÔûâÔûàÔûåÔûç
```

**Comment by Chris911** [comment]
The sensors use different keys in older macs. I think there's a pull request here to support more versions but I really have a hard time finding time to work on this project. I'll try my best.

**Comment by timball** [comment]
word thanks

**Comment by mongrelx** [comment]
in pull request there is generic key scanner and support for configuration files to enable /disable key reading .. if someone is interested i'll add configuration option for thresholds too

**Comment by Chris911** [comment]
iStats now has to option to scan and use specific sensors. See README.
