### ISSUE TITLE
different CPU temp to Intel Power Gadget

### ISSUE THREAD

**Issue by John-Colvin** [Chris911/iStats#19]
https://software.intel.com/en-us/articles/intel-power-gadget-20 gives CPU temperature values that are approx. 22ºC warmer than what iStats reports.

Hardware:
Macbook Pro 13" retina mid 2014, Core i5 (I5-4278U)

**Comment by Chris911** [comment]
Intel might be using different sensors. If you take a look at [this file](https://github.com/Chris911/iStats/blob/master/ext/osx_stats/smc.h#L42) you'll see which sensor key iStats uses for Apple's System Management Control (SMC) tool.

**Comment by tonin** [comment]
It would be nice if iStats could report different (as chosen by the user) CPU/GPU temperature.  This table could come handy: https://www.assembla.com/spaces/fakesmc/wiki

**Comment by Chris911** [comment]
Nice list! I'd like to do a new pass and add more sensors but I don't really have time right now. I'll definitely use this list as a reference when I do. 

Also always opened to pull requests and testers!

**Comment by mongrelx** [comment]
Check out my pull request... It probes all keys and is configurable via config file

**Comment by Chris911** [comment]
Version 1.1.0 now includes a way to scan for new sensors (thanks to @mongrelx). Check the [Advanced usage](https://github.com/Chris911/iStats#advanced-usage) of the README.
