### ISSUE TITLE
battery info seems quite slow on my Yosemite mid 2009 mbp with an HDD.

### ISSUE THREAD

**Issue by Arthur2e5** [Chris911/iStats#20]
Every time when I run `istats`, all information but the battery stats appear quickly. But for each battery info, it takes ~0.5 seconds for each item to appear.

When I dig into the source, I got a lot of `ioreg -l | grep some_keyword` in `battery.rb`. When I run `time ioreg -l >/dev/null` in bash, I got:
```
real	0m0.552s
user	0m0.109s
sys	0m0.312s
```

This is quite close to the delays between each item. It seems that first caching the output as a variable to store internally and then use ruby builtins to match regexes may be a better idea, since `ioreg` is really, really slow…

**Comment by Arthur2e5** [comment]
On my mac the battery seems to be named as `AppleSmartBattery`. Doing `ioreg -n AppleSmartBattery` is also faster than doing `ioreg -l`. 

I don't know if the name of the battery varies between different macs. If so, `ioreg -k Battery` may be a better idea.

**Comment by Arthur2e5** [comment]
All done, yeah!

**Comment by Chris911** [comment]
Also released a new version of the gem as v1.0.0.

Thanks for your contributions!

**Comment by Arthur2e5** [comment]
Saw that already. Awesome.

Unluckily the chinese GFW is still stopping me to connect to rubygems.org :(. The good news is I already have a self-packed gem installed right after I sent the PRs so everything is just fine.

By the way you can add my almost broken MacBook Pro 2009 mid with OS X 10.10.3 & Ruby 2.0.0 to the tested list since for a few months I will still stay with it and keep something like `while sleep 20; do istats; done` running in my shell…

**Comment by Chris911** [comment]
Ah that sucks. Great that you could package the gem yourself.
