### ISSUE TITLE
cycleCount or cycle_count

### ISSUE THREAD

**Issue by Amorymeltzer** [Chris911/iStats#25]
Originating in 879bda31, the help and readme suggests `istats battery cycleCount` while command.rb requires `istats battery cycle_count`, so naturally the former fails while the latter works.  Raising an issue rather than PR to decide which to prefer, as this the only two-word option.

**Comment by Chris911** [comment]
Thanks. I'll go with `cycle_count` and update the help text.

**Comment by Chris911** [comment]
Just released v1.0.1 which contains the fix.

Thanks for your contribution.
