### ISSUE TITLE
Not working on El Capitan public beta

### ISSUE THREAD

**Issue by spilja** [Chris911/iStats#26]
I had iStats installed in Yosemite, but when trying to run it in El Capitan I get command not found.

I tried installing it again and this is the output I get

    sudo gem install iStats
    Password: 
    Building native extensions.  This could take a while...
    ERROR:  Error installing iStats:
	    ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
    creating Makefile

    make "DESTDIR="
    make: *** No rule to make target             `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.    10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-    darwin15/ruby/config.h', needed by `smc.o'.  Stop.

    Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/iStats-1.0.1 for inspection.
    Results logged to /Library/Ruby/Gems/2.0.0/gems/iStats-1.0.1/ext/osx_stats/gem_make.out

**Comment by Chris911** [comment]
Noted. I'll find someone to debug this with. Not upgrading to EL Capitan just yet for that reason.

**Comment by Syfaro** [comment]
I can't replicate this, it installed perfectly fine for me on El Capitan after having been installed on Yosemite.

**Comment by spilja** [comment]
@Syfaro that did it, thank you!

**Comment by Chris911** [comment]
Alright closing this. If more people have this issue I'll add instructions to the README. Thanks.

**Comment by awhit012** [comment]
One of my students is having this issue. xcode is freshly updated too.

**Comment by vjm** [comment]
+1

**Comment by Chris911** [comment]
@vjm I installed El Capitan last week and iStats works just fine. Make sure you run `xcode-select --install` to get the latest command line tools.

**Comment by vjm** [comment]
@Chris911 I was +1-ing the solution -- agreed that fixes things!

**Comment by Chris911** [comment]
Oh alright. Thanks :+1:

**Comment by caseykulm** [comment]
Same problem on OSX 10.10.5 Yosemite. Same solution resolved it for me as well.
