### ISSUE TITLE
Help output bug ("set" instead of "enable")

### ISSUE THREAD

**Issue by matiasherranz** [Chris911/iStats#29]
Hi!
Here it says "set" and should be "enable". Took me a couple of minutes to figure out.

https://github.com/Chris911/iStats/blob/master/lib/iStats/smc.rb#L120

**Comment by matiasherranz** [comment]
PR with the fix: https://github.com/Chris911/iStats/pull/30

**Comment by Chris911** [comment]
v1.1.1 published with the fix.
