### ISSUE TITLE
not working on el capitan

### ISSUE THREAD

**Issue by gurkanboll** [Chris911/iStats#33]
Just downloaded and upgrade to 10.11.1 El Capitan and now i cant seem to `iStats` in terminal, is this a known issue?

**Comment by Chris911** [comment]
See #26. Try running `xcode-select --install` and then install iStats again.

**Comment by gurkanboll** [comment]
hm, missed that one, thank you, however, that caused another problem with permission denied which was solved following this [link](http://stackoverflow.com/questions/32891965/error-while-executing-gem-errnoeperm-operation-not-permitted)

`sudo gem install -n /usr/local/bin iStats`

**Comment by khoairan** [comment]
I also have problem when install Istats. 
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Gems/2.0.0/gems/iStats-1.2.0/.gitignore
How to fix this matter?
