### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pahakalle** [Chris911/iStats#38]
would be nice to have a way to loop the code, without using watch or other methods

**Comment by pastullo** [comment]
yeah!

**Comment by mongrelion** [comment]
@pahakalle what do you mean by looping the code? Also, maybe update the title of the issue to something more descriptive.
👍

**Comment by vitorgalvao** [comment]
```bash
while true; do
  istats
  sleep 3 # in seconds
done
```
