### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by miguelPerezOntiveros** [Chris911/iStats#40]
Problem Installing it.
I'm running 10.11.6 on a 15" '16 MBP.

`
> sudo gem install iStats
Password:
Fetching: sparkr-0.4.1.gem (100%)
Successfully installed sparkr-0.4.1
Fetching: parseconfig-1.0.8.gem (100%)
Successfully installed parseconfig-1.0.8
Fetching: iStats-1.2.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing iStats:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `smc.o'.  Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/iStats-1.2.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/iStats-1.2.0/ext/osx_stats/gem_make.out
`

**Comment by Chris911** [comment]
See #26. Try running `xcode-select --install` and then install iStats again.

**Comment by miguelPerezOntiveros** [comment]
It worked! I will close this issue, thanks.
