### ISSUE TITLE
Feature Request: Parameter to exclude colors in output

### ISSUE THREAD

**Issue by lenzirodrigo** [Chris911/iStats#41]
I would like to run and log the values of IStats watching the command every 5 mins.
The output contains color values that are only interpreted by the shell:

<img width="545" alt="screen shot 2016-10-10 at 10 33 43 am" src="https://cloud.githubusercontent.com/assets/2400358/19237808/12850a76-8ed5-11e6-81f8-25460d4e43bb.png">

Would it be possible to exclude those color chars from the output?

Sorry if this is not the way request a feature.
Thanks!

**Comment by Chris911** [comment]
That's a fair request. I'll see what I can do.

**Comment by Chris911** [comment]
Just released iStats 1.3.0 with support of the `--no-graphs` command line arg.

**Comment by lenzirodrigo** [comment]
That was fast. Thanks!

**Comment by jgreen210** [comment]
It should generally be possible to auto detect if terminal escape codes or graphs that require colour should be output based on:

http://ruby-doc.org/core-2.4.1/IO.html#method-i-tty-3F
https://stackoverflow.com/questions/6671716/difference-between-stdout-and-stdout-in-ruby
