### ISSUE TITLE
Slight issue with iStats and Watch

### ISSUE THREAD

**Issue by Mirppc** [Chris911/iStats#48]
I thought i would use iStats with the watch command so i would get a real time tempature update every -n X seconds.  Thou using the watch command i get the text read out, the ncurses graphics do now show up well or at all.

command used:
*watch -n 10 iStats*

visual output:
http://paste.opensuse.org/69335383

System information:
 OS: OS X 10.11.6 • CPU: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2.40GHz) • Memory: 8.0 GiB Total (2.6 GiB Free) • Storage: 123.7 GB / 311.7 GB (188.0 GB Free) • VGA: NVIDIA GeForce 320 • Uptime: 5w 1d 20h 46m 2s

**Comment by picatz** [comment]
I would try the `--color` option for watch which should interpret ANSI color and style sequences better. So, you could do this:
```shell
$ watch --color -n 10 iStats
```

**Comment by Mirppc** [comment]
Thanks for the spiffy response.  It looks a little cleaner now albit none of the nice graphs.

Command used:
*watch --color -n 10 iStats*

Visual Output:
http://paste.opensuse.org/61434108

**Comment by picatz** [comment]
Glad I could help! Sorry about the lack of nice graphs.

**Comment by Mirppc** [comment]
Not a Huge Deal.  To me is is more important i keep an eye on the temperatures since the thermal readings wont show up in Glances.

**Comment by picatz** [comment]
Just for giggles: Have you thought about re-implementing the watch command in some sort of simple ruby/bash script to call iStats every 10 seconds? 

You could still have the colored output too: 

```ruby
while true
  puts `clear`   # clear screen
  puts `iStats`  # run iStats command
  sleep 10       # sleep for 10 seconds
end
```

**Comment by Chris911** [comment]
Yep doesn't seem to work with `watch` here as well. I'd go with @picatz suggestion if you really want to the graphs. I do this for a few other commands when `watch` breaks the output. This works nicely with the date on top: `while true; do clear; date; istats; sleep 10; done;`

I'm going to close this issue because I don't think this is something I can fix on iStats. Seems to be a watch restriction.
