### ISSUE TITLE
No such file or directory - ioreg

### ISSUE THREAD

**Issue by stea4lth** [Chris911/iStats#49]
iStats was working fine and all of the sudden I started getting this error. Any suggestions?

--- CPU Stats ---
CPU temp: 51.13°C ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system: 1
Fan 0 speed: 1295.0 RPM  ▁▂▃▅▆▇

--- Battery Stats ---
Battery health: Good
/Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:49:in ``': No such file or directory - ioreg (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:49:in `cycle_count'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:41:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:70:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:40:in `delegate'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:20:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/bin/istats:8:in `<top (required)>'
	from /usr/local/bin/istats:23:in `load'
	from /usr/local/bin/istats:23:in `<main>'

**Comment by Chris911** [comment]
`ioreg` is a system command. Do you get the same error if you enter `ioreg` in your command line?

**Comment by stea4lth** [comment]
It says command not found

**Comment by Chris911** [comment]
That's weird. `ioreg` should be available by default on OS X. What shell/terminal are you using?

**Comment by stea4lth** [comment]
I am using zsh.

**Comment by NathanZepol** [comment]
I am having the same issue myself, on ZSH.

`/Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:49:in ``': No such file or directory - ioreg (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:49:in `cycle_count'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/battery.rb:41:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:70:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:40:in `delegate'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/lib/iStats/command.rb:20:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/iStats-1.4.0/bin/istats:8:in `<top (required)>'
	from /usr/local/bin/istats:23:in `load'
	from /usr/local/bin/istats:23:in `<main>'`

**Comment by stea4lth** [comment]
My path variables were broken...  Check out this link
https://stackoverflow.com/questions/43530628/how-to-install-ioreg

**Comment by Chris911** [comment]
Thanks for replying back with the fix @stea4lth. I'm going to close this issue as it is not directly related to iStats.

**Comment by NathanZepol** [comment]
There is nothing wrong with my path variables, and I am still having the issue.

```
→ which ioreg
/usr/sbin/ioreg
```
