### ISSUE TITLE
unable to convert "\xCA" ...

### ISSUE THREAD

**Issue by Bigg-Iron** [Chris911/iStats#50]
## System info:
 macOS Sierra
 version 10.12.4

## Install completed, but with the following errors (see image attatched):

```
 unable to convert "\xCA" from ASCII-8BIT to UTF-8 for ext/osx_stats/osx_stats.bundle, skipping
 unable to convert "\xCA" from ASCII-8BIT to UTF-8 for ext/osx_stats/smc.o, skipping
 unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/osx_stats.bundle, skipping 

```
 
<img width="673" alt="screen shot 2017-05-01 at 3 23 32 pm" src="https://cloud.githubusercontent.com/assets/19870186/25597682/07b6a94c-2e85-11e7-9a27-f9cc756b4add.png">

**Comment by Chris911** [comment]
This is just documentation parsing warnings. Doesn't impact the installation.
