### ISSUE TITLE
Sparklines don't respect temperature units

### ISSUE THREAD

**Issue by jgrosso** [Chris911/iStats#57]
First, thanks for this awesome utility!

When I do not use the `-f` flag, my CPU temperature is normal (say, 44 degrees Celsius). However, when I enable `-f`, the CPU temperature jumps appropriately (say, to 110 degrees Fahrenheit), and the sparkline flashes red (I'm assuming because the new value is above the threshold designed for Celsius temperatures).

**Comment by sterpe** [comment]
I also have this issue on High Sierra.  41C => ~106F, but Sparkline thinks this is an emergency when using F.

**Comment by Chris911** [comment]
I'll take a look at this issue this week.

**Comment by Chris911** [comment]
This was fixed in https://github.com/Chris911/iStats/pull/62 and released in [v1.5.1](https://rubygems.org/gems/iStats/versions/1.5.1).

**Comment by sterpe** [comment]
Nice. Thanks!
