### ISSUE TITLE
istats scan -f shows all meters as critical

### ISSUE THREAD

**Issue by collinanderson** [Chris911/iStats#63]
Thanks for all of your work on this program. It's great.

if run `istats scan -f` the meters seem to use the Fahrenheit temperature for the meter, which makes them all appear critical, when they're actually fine.

Same is true if I enable a key, the extra meter changes colors depending on whether I use the `-f` flag (though the default meters are fine)

```
$ istats -v
iStats v1.5.1
```

**Comment by Chris911** [comment]
Arghh we just fixed this for the CPU stats. Will make the proper fix for the scan and extra commands as well.

**Comment by Chris911** [comment]
Fixed and released in v1.5.2.

**Comment by OverZealous** [comment]
I just installed v1.5.2, and I'm seeing this for all the extras still. 😕 

Freaked me out for a moment!

![screen shot 2018-02-21 at 11 14 23 pm](https://user-images.githubusercontent.com/965719/36520081-fb7b42d4-175c-11e8-8378-002cb9a88005.png)

This is on a 2013 Mac Pro (trashcan).

**Comment by Chris911** [comment]
I'm able to reproduce locally as well. Will release a fix as soon as I can.

**Comment by Chris911** [comment]
This issue has been fixed in v1.6.1.
