### ISSUE TITLE
Fans speed display abnormally, does any overflow error happen in new MacBook Pro 2018

### ISSUE THREAD

**Issue by RobinsonWong** [Chris911/iStats#66]
screenshot in iStats vs.  in Macs Fan control
![image](https://user-images.githubusercontent.com/4406853/43362516-6c4cbc26-931e-11e8-83a5-f7adfad13922.png)
does any overflow error happen in new MacBook Pro 2018?
any help will be appreciated, thank you!

**Comment by Chris911** [comment]
There's already a discussion about this going on here https://github.com/Chris911/iStats/issues/65. Unfortunately I don't have access to a 2018 Macbook so I can't debug the issue.

**Comment by RobinsonWong** [comment]
OK, apology for not viewing the issue list carefully.
 I see you already have the bug fixed!  Great!   
Thank you!!!
