### ISSUE TITLE
Fan speed reading is way off

### ISSUE THREAD

**Issue by moo7md** [Chris911/iStats#68]
Hello there,

I noticed that when I use istats on my new MacBook Pro 15 2018, the fan speed seems way off. 
https://imgur.com/a/jTpEk9X
Please let me know what do you find.

**Comment by Chris911** [comment]
This should have been fixed yesterday. Can you make sure you're using the latest version.

**Comment by Chris911** [comment]
Please reopen this issue if you still have the issue on v1.6.2.
