### ISSUE TITLE
broken after gem pristine iStats --version 1.6.1

### ISSUE THREAD

**Issue by pscott-au** [Chris911/iStats#70]
was working fine - noticed line on executing 
Ignoring iStats-1.6.1 because its extensions are not built.  Try: gem pristine iStats --version 1.6.1

so I tried to run "gem pristine iStats --version 1.6.1" and now it's broken.

$ gem pristine iStats --version 1.6.1
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
peter$ sudo gem pristine iStats --version 1.6.1
Password:
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1/ext/osx_stats
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181029-60065-18ohgui.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1/ext/osx_stats
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1/ext/osx_stats
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `smc.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/iStats-1.6.1/gem_make.out

**Comment by Chris911** [comment]
Same error as #69. Also can't reproduce on my computer 😕

**Comment by pscott-au** [comment]
I found a solution for my case. 
I did a brew install ruby which updated my ruby version ( Think it was 2.3.0 and updated to 2.5.3 ) and the sudo gem install iStats and it's working again.

**Comment by peterpalfi** [comment]
> I found a solution for my case.
> I did a brew install ruby which updated my ruby version ( Think it was 2.3.0 and updated to 2.5.3 ) and the sudo gem install iStats and it's working again.

thank you it solved for me
