### ISSUE TITLE
Autorefresh option

### ISSUE THREAD

**Issue by CrossfireX** [Chris911/iStats#74]
Love the iStat app, delivers all the info in one place. Now, is it possible to integrate autorefresh option? So it's dynamically refreshed every second similar to htop/gotop on linux?

**Comment by Chris911** [comment]
I don't think I'll implement this but I know a lot of people are using `watch` for this. Eg. `watch --color -n 10 iStats` to refresh every 10 seconds. If that doesn't work for you it's also possible to do it was small bash scripts like:
```bash
while true
  puts `clear`   # clear screen
  puts `iStats`  # run iStats command
  sleep 10       # sleep for 10 seconds
end
```
or
```bash
while true; do clear; date; istats; sleep 10; done;
```

You can alias any of these to a command like `istats-watch`.

**Comment by CrossfireX** [comment]
Spot on. 
Thx!
