### ISSUE TITLE
Failed installation on MacOS 10.14.5 

### ISSUE THREAD

**Issue by seamusdemora** [Chris911/iStats#78]
MacOS 10.14.5, no Homebrew (really do NOT want it), no complete Xcode install, but do have parts of it installed (cmd line tools???)

Looked at [this issue](https://github.com/Chris911/iStats/issues/69), but so many trial-and-error solutions offerred, it's unclear exactly what the resolution is. Here's the error I get:

```
$ sudo gem install iStats
Fetching: sparkr-0.4.1.gem (100%)
Successfully installed sparkr-0.4.1
Fetching: parseconfig-1.0.8.gem (100%)
Successfully installed parseconfig-1.0.8
Fetching: iStats-1.6.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing iStats:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1/ext/osx_stats
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190529-1855-1jap8gj.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/iStats-1.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/iStats-1.6.1/gem_make.out  
```

**Comment by Chris911** [comment]
Try `xcode-select --install` first. It installs tools required to build the package. Then `sudo gem install iStats`.

**Comment by seamusdemora** [comment]
Yes! Thanks, that did it: 

```
$ xcode-select --install
xcode-select: note: install requested for command line developer tools  
```  
Which spawned a gui for install of the command line tools & authentication, and then: 

```
$ sudo gem install iStats
Password:
Building native extensions.  This could take a while...
Successfully installed iStats-1.6.1
Parsing documentation for iStats-1.6.1
Installing ri documentation for iStats-1.6.1
Done installing documentation for iStats after 0 seconds
1 gem installed
```  
And finally: 
```
$ istats cpu
CPU temp:               35.06°C     ▁▂▃▅▆▇
``` 
Just one other question: As a command line tool, I imagined there would be a manual, but `man istats` yields nothing. Yet, the install confirmed documentation was installed. What am I missing?

**Comment by Chris911** [comment]
No `man` entry but you can use `istats --help` to see all the available options.

**Comment by seamusdemora** [comment]
OK, thanks... so the `--help` option is the documentation?

**Comment by Chris911** [comment]
Yes. If you have any other questions you can let me know.
