### ISSUE TITLE
Not working in macOS 10.15 Catalina

### ISSUE THREAD

**Issue by Liampor** [Chris911/iStats#85]
Hello,

I have updated to macOS 10.15 Catalina, then iStats does not work any more.

> \> iStats
zsh: /usr/local/bin/istats: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory

It seems, Rubyl are not included in new macOS.

my Ruby version
>\>ruby -v
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

Thanks

**Comment by tomtastic** [comment]
`$ brew install ruby`
You might want to do this for Ruby, PERL, Python3 as MacOS isn't including them from Catalina onwards

**Comment by phyng** [comment]
`sudo gem install iStats` works for me in macOS 10.15 Catalina:
```
➜  ~ sudo gem install iStats
Password:
Fetching iStats-1.6.1.gem
Fetching sparkr-0.4.1.gem
Fetching parseconfig-1.0.8.gem
Successfully installed sparkr-0.4.1
Successfully installed parseconfig-1.0.8
Building native extensions. This could take a while...
Successfully installed iStats-1.6.1
Parsing documentation for sparkr-0.4.1
Installing ri documentation for sparkr-0.4.1
Parsing documentation for parseconfig-1.0.8
Installing ri documentation for parseconfig-1.0.8
Parsing documentation for iStats-1.6.1
Installing ri documentation for iStats-1.6.1
Done installing documentation for sparkr, parseconfig, iStats after 0 seconds
3 gems installed
➜  ~ istats           
--- CPU Stats ---
CPU temp:               44.56°C     ▁▂▃▅▆▇
......
```

**Comment by Chris911** [comment]
Try reinstalling the command line tools with `xcode-select --install`.

**Comment by Liampor** [comment]
> Try reinstalling the command line tools with `xcode-select --install`.

still not working with the same error message

**Comment by Liampor** [comment]
> `sudo gem install iStats` works for me in macOS 10.15 Catalina:
> 
> ```
> ➜  ~ sudo gem install iStats
> Password:
> Fetching iStats-1.6.1.gem
> Fetching sparkr-0.4.1.gem
> Fetching parseconfig-1.0.8.gem
> Successfully installed sparkr-0.4.1
> Successfully installed parseconfig-1.0.8
> Building native extensions. This could take a while...
> Successfully installed iStats-1.6.1
> Parsing documentation for sparkr-0.4.1
> Installing ri documentation for sparkr-0.4.1
> Parsing documentation for parseconfig-1.0.8
> Installing ri documentation for parseconfig-1.0.8
> Parsing documentation for iStats-1.6.1
> Installing ri documentation for iStats-1.6.1
> Done installing documentation for sparkr, parseconfig, iStats after 0 seconds
> 3 gems installed
> ➜  ~ istats           
> --- CPU Stats ---
> CPU temp:               44.56°C     ▁▂▃▅▆▇
> ......
> ```

still not woking, but thanks
sudo gem install iStats                          
Building native extensions. This could take a while...
Successfully installed iStats-1.6.1
Parsing documentation for iStats-1.6.1
Installing ri documentation for iStats-1.6.1
Done installing documentation for iStats after 0 seconds
1 gem installed
╭─  ~ 
╰─ istats
zsh: /usr/local/bin/istats: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory

**Comment by Chris911** [comment]
Did you try reinstalling iStats? The error is looking for for a ruby executable in the `2.3` folder but from your `ruby -v` it looks like you have 2.6 installed.

**Comment by Liampor** [comment]
> Did you try reinstalling iStats? The error is looking for for a ruby executable in the `2.3` folder but from your `ruby -v` it looks like you have 2.6 installed.

I have tried "sudo gem install iStats" and brew install ruby... not working

**Comment by Liampor** [comment]
> Did you try reinstalling iStats? The error is looking for for a ruby executable in the `2.3` folder but from your `ruby -v` it looks like you have 2.6 installed.

I think iStats needs ruby 2.3， but new macOS remove the ruby 2.3 and my user-ruby is Ruby 2.6

**Comment by Chris911** [comment]
Try `gem uninstall iStats` and then `gem install iStats`

**Comment by Liampor** [comment]
> Try `gem uninstall iStats` and then `gem install iStats`

still...

![image](https://user-images.githubusercontent.com/19495916/66726594-de010c00-ee6c-11e9-9c2e-e51c874d20ad.png)

**Comment by Chris911** [comment]
Ah try `istats` all lowercase instad of `iStats`.

**Comment by Liampor** [comment]
> Ah try `istats` all lowercase instead of `iStats`.

same error  :-)

**Comment by Chris911** [comment]
I don't know then. Still find it weird that the error is for 2.3 and you have 2.6 installed. I just uninstalled and reinstalled on my machine running Catalina and have no errors. I didn't have to use `sudo`.

**Comment by Liampor** [comment]
> I don't know then. Still find it weird that the error is for 2.3 and you have 2.6 installed. I just uninstalled and reinstalled on my machine running Catalina and have no errors. I didn't have to use `sudo`.

thanks, use "gem install iStats" it gives more errors

![image](https://user-images.githubusercontent.com/19495916/66726840-27059000-ee6e-11e9-86a9-87c1e32f0631.png)

**Comment by phyng** [comment]
@Liampor Inferred from your log, take a look at `/usr/local/bin/istats`, update first line to 2.6  maybe can solve this:
```
➜   which ruby
/usr/bin/ruby
 ➜  cat /usr/local/bin/istats
#!/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
```

**Comment by Liampor** [comment]
> @Liampor Inferred from your log, take a look at `/usr/local/bin/istats`, update first line to 2.6 (or the output of `which ruby`) maybe can solve this:
> 
> ```
> ➜   which ruby
> /usr/bin/ruby
>  ➜  cat /usr/local/bin/istats
> #!/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> ```

#!/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby 

gives 

![image](https://user-images.githubusercontent.com/19495916/66728649-bc0d8680-ee78-11e9-9e56-a3a9abcbcf79.png)

**Comment by Liampor** [comment]
@Chris911 @phyng  

Finally solved!  Thank you all!

I have two Ruby path:

1. `/usr/local/opt/ruby/bin/ruby (default, installed by Homebrew)`
2. `/usr/bin/ruby`

If set default ruby-path to `/usr/bin/ruby` und reinstall iStats by `sudo gem install iStats` then edit `/usr/local/bin/istats` headline to `#!/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby`

it works fine !

**Comment by guchongxi** [comment]
@Liampor I have same problem, two Ruby path; and I don't know how to set default ruby-path

**Comment by Liampor** [comment]
> @Liampor I have same problem, two Ruby path; and I don't know how to set default ruby-path

Step 1:
set ruby-path to `/usr/bin/ruby`
to do this, you can edit your Terminal profile，for example in ZSH
`export PATH="/usr/bin:$PATH"`

Step 2: 

reinstall iStats

uninstall: `sudo gem uninstall iStats`
then reinstall: `sudo gem install iStats`

worked!

If you want to use other Ruby-path, you can edit the terminal profile later.

ps. 用我的蹩脚英语和中国人对话好奇怪。。

**Comment by guchongxi** [comment]
哈哈，感谢感谢，已经成功安装。

Ting Sun <notifications@github.com> 于 2019年10月17日周四 21:49写道：

**Comment by yuzuri** [comment]
Hi all,
I also got same trouble and reached here.
@Liampor, thank you for giving me the answer!

> > Did you try reinstalling iStats? The error is looking for for a ruby executable in the `2.3` folder but from your `ruby -v` it looks like you have 2.6 installed.
> 
> I think iStats needs ruby 2.3， but new macOS remove the ruby 2.3 and my user-ruby is Ruby 2.6

I installed ruby 2.3 via mac ports and changed the default ruby and succeeded to install iStats.

```
% sudo port install ruby23
% sudo port install ruby_select
% sudo port select --set ruby ruby23
% sudo gem install iStats -n /usr/local/bin 
```

environment : Mac OSX catalina (10.15.7)

**Comment by Nakilon** [comment]
When useing Homebrew I recommend installing Ruby via `brew install rbenv` and following the instructions.
