### ISSUE TITLE
Access errors upon install - Errno::EACCE

### ISSUE THREAD

**Issue by aaronzshey** [Chris911/iStats#89]
I have ruby 2.6.0 on macOS Catalina 10.15.2.  I tried installing iStats in my normal account, but received a lack of write access error.  Subsequently, I logged into my administrator account and oddly also received an unable to write error… I manually changed the permissions for the target folder and tried installing again, only to receive even more errors ending with Errno::EACCE.  Is this an issue with my configuration?
The specific final line was
    Permission denied @ rb_sysopen - /Library/Ruby/Gems/2.6.0/cache/parseconfig-1.0.8.gem

**Comment by MrNotch9** [comment]
use this command:
``sudo gem install iStats``
