### ISSUE TITLE
Misreporting CPU temp

### ISSUE THREAD

**Issue by wjr2** [Chris911/iStats#9]
I've installed iStats on a mid-2007 iMac that runs OS 10.9.4 and does not use Homebrew. There are two odd bits:
1) the reported CPU temperature is -127.0 C -- great for condensed matter physics experiments! :p 
2) fan 0 always reports 0 RPM (I note that this may be a hardware issue.) 

The installation went like so:
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
$ rvm use system
$ sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install iStats

**Comment by Chris911** [comment]
iStats now has to option to scan and use specific sensors. See README.
