### ISSUE TITLE
iStats stopped working: "Failed to execute process '/usr/local/bin/istats'"

### ISSUE THREAD

**Issue by Aracki** [Chris911/iStats#91]
After a while, the app stopped working. I am getting the following error:
```
Failed to execute process '/usr/local/bin/istats'. Reason:
The file '/usr/local/bin/istats' specified the interpreter '/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby', which is not an executable command.
```

**Comment by xrei** [comment]
Same issue here, but different error message

```zsh: /usr/local/bin/istats: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory```

**Comment by Aracki** [comment]
I've solved the issue with following commands:
```
rm /usr/local/bin/istats
sudo gem install -n /usr/local/bin iStats
```
